version: "3.9"
services:
  couchdb:
    container_name: couchdb
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USERNAME:?Couch credentials are required}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:?Couch credentials are required}
    volumes:
      - dbdata:/opt/couchdb/data
volumes:
  dbdata: