apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "Inventory: Coming Soon™"
