apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb
spec:
  selector:
    matchLabels:
      app: couchdb
  serviceName: "couchdb"
  replicas: 1
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb
        env:
          - name: COUCHDB_USER
            value: ${COUCHDB_USERNAME:?Couch credentials are required}
          - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:?Couch credentials are required}
        volumeMounts:
        - mountPath: "/opt/couchdb/data"
          name: inventory-data-pvc
  volumeClaimTemplates:
  - metadata:
      name: inventory-data-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: do-block-storage 
 
 
 
 
