apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - inventory.northroad-craftworks.com
    secretName: inventory-tls
  rules:
  - host: "inventory.northroad-craftworks.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: inventory
            port:
              number: 80
