apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: inventory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: ghcr.io/northroad-craftworks/inventory:${APP_VERSION}
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: '8080'
        - name: LOG_LEVEL
          value: verbose
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: secret
        - name: COUCHDB_URL
          value: http://database-couchdb:5984
        - name: COUCHDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-couchdb
              key: adminUsername
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-couchdb
              key: adminPassword
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-oauth-secret
              key: clientId
              optional: true
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-oauth-secret
              key: clientSecret
              optional: true
        - name: ALLOW_ANONYMOUS
          value: 'false'
        resources:
          limits:
            cpu: 50m
            memory: 65Mi
          requests:
            cpu: 25m
            memory: 32Mi
