openapi: "3.0.0"

info:
  title: Northroad Craftworks Inventory
  version: Development

tags:
  - name: Service
    description: Information about the service's status
  - name: Inventory Items
    description: Manage inventory items
  - name: Transactions
    description: Buy, sell, manufacture, and adjust items in inventory

paths:
  /status:
    get:
      operationId: getStatus
      summary: Get the service status
      tags: [Service]
      responses:
        "200":
          description: General information about the health and status of the service.
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    description: Current release version
                    example: 1.0.0
  /items:
    get:
      operationId: listItems
      summary: List inventory items
      tags: [Inventory Items]
      parameters:
        - in: query
          name: hidden
          description: Filter by hidden status
          schema:
            type: boolean
        - in: query
          name: account
          description: Filter by account
          schema:
            $ref: "#/components/schemas/Item/properties/account"
      responses:
        "200":
          description: All inventory items
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
            "text/plain":
              schema:
                description: A text list of all the items in inventory
        default:
          $ref: "#/components/responses/Error"

  /item/{itemId}:
    parameters:
      - $ref: "#/components/parameters/itemId"
    get:
      operationId: readItem
      summary: Get an inventory item
      tags: [Inventory Items]
      responses:
        "200":
          description: Details about the inventory item
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Item"
        default:
          $ref: "#/components/responses/Error"
    put:
      operationId: createItem
      summary: Create an inventory item
      tags: [Inventory Items]
      requestBody:
        description: Inventory item data
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "201":
          description: Inventory item created
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Item"
        "200":
          description: Inventory item updated
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Item"
        default:
          $ref: "#/components/responses/Error"
    
    patch:
      operationId: updateItem
      summary: Update an inventory item
      tags: [Inventory Items]
      requestBody:
        description: Updates to inventory data
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "200":
          description: Inventory item updated
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Item"
        default:
          $ref: "#/components/responses/Error"
    delete:
      operationId: deleteItem
      summary: Delete an unused inventory item
      description: |
        Inventory items can only be deleted if they haven't been used for any transactions and don't exist on any
        ledgers. Once an inventory item has been bought, sold, or manufactured, it cannot be deleted until **all**
        transactions which reference it have been deleted or archived.
      tags: [Inventory Items]
      responses:
        "200":
          description: Delete successfully
        default:
          $ref: "#/components/responses/Error"

  /buy:
    post:
      operationId: recordBuyTransaction
      summary: Record the purchase of new inventory
      tags: [Transactions]
      requestBody:
        description: Transaction details
        content:
          "application/json":
            schema:
              required: [id, type, itemsAdded, totalCost]
              $ref: "#/components/schemas/Transaction"
      responses:
        "501":
          description: Not implemented

  /sell:
    post:
      operationId: recordSellTransaction
      summary: Record the sale of inventory to customers
      tags: [Transactions]
      requestBody:
        description: Transaction details
        content:
          "application/json":
            schema:
              required: [id, type, itemsRemoved, totalCost]
              $ref: "#/components/schemas/Transaction"
      responses:
        "501":
          description: Not implemented

  /make:
    post:
      operationId: recordManufactureTransaction
      summary: Manufacture new inventory items from existing ones
      tags: [Transactions]
      requestBody:
        description: Transaction details
        content:
          "application/json":
            schema:
              required: [id, type, itemsAdded, itemsRemoved, totalCost]
              $ref: "#/components/schemas/Transaction"
      responses:
        "501":
          description: Not implemented

  /adjust:
    post:
      operationId: recordAuditTransaction
      summary: Manually adjust inventory items as the result of loss, damage, waste, or audits
      tags: [Transactions]
      deprecated: true
      responses:
        "501":
          description: Not implemented

  /transaction/{transactionId}:
    parameters:
      - $ref: "#/components/parameters/transactionId"
    get:
      operationId: getTransaction
      summary: Get a record of a transaction
      tags: [Transactions]
      responses:
        "200":
          description: Details about the transaction
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Transaction"
        default:
          $ref: "#/components/responses/Error"


components:
  parameters:
    itemId:
      name: itemId
      in: path
      required: true
      description: The `id` of the desired item
      schema:
        readOnly: false
        $ref: "#/components/schemas/Item/properties/id"
    transactionId:
      name: transactionId
      in: path
      required: true
      description: The `id` of the desired transaction
      schema:
        readOnly: false
        $ref: "#/components/schemas/Transaction/properties/id"

  responses:
    Error:
      description: Something went wrong
      content:
        'text/plain':
          schema:
            type: string
            description: A description of the problem
            example: 'Internal server error'


  schemas:
    Purchase:
      type: object
      description: |
        A transaction which purchases items and adds them to inventory.
        Multiple items can be purchased and the values of each are provided by the user.
        Additional costs may also be stored for record-keeping, but these are not included in the item values.
      required: [id, type, items]
      additionalProperties: false
      properties:
        id:
          readOnly: true
          description: Globally-unique transaction ID
          type: string
          pattern: "[a-z0-9-]+"
        date:
          type: string
          description: When the transaction occured.
          format: date-time
        items:
          description: A list of all the items added to inventory by this transaction
          type: array
          items:
            type: object
            required: [id, quantity, cost]
            additionalProperties: false
            properties:
              id:
                type: string
                description: ID of the item affected by the transaction
              quantity:
                type: number
                description: Amount of the item purchased or created
              cost:
                type: number
                minimum: 0
                description: |
                  The total cost for the items purchased.
                  This value must be positive, as it is adding to the total value of inventory.
        additionalCosts:
          description: |
            Other costs, such as tax or shipping, that are related to the purchase.
            These are only stored for reference and aren't included in the value of the added items.
          type: array
          items:
            type: object
            required: [name, cost]
            additionalProperties:
              description: Additional information, such as tax jurisdiction, that may be needed for records
              type: string
            properties:
              name:
                type: string
                example: shipping
              cost:
                type: number
                description: |
                  The value of the additional cost.
                  Use a positive value for items that increase costs, such as taxes and shipping.
                  Use a negative value for items that reduce costs, such as refunds or credits.
        totalCost:
          type: number
          description: The total cost of the transaction, including all `materials` and `additionalCosts`.

    Sale:
      type: object
      description: |
        A transaction which sells items and removes them from inventory.
        Multiple items may be sold and the values of each are determined at the time of the transaction.
      required: [id, items, totalCost]
      additionalProperties: false
      properties:
        id:
          readOnly: true
          description: Globally-unique transaction ID
          type: string
          pattern: "[a-z0-9-]+"
        date:
          type: string
          description: When the transaction occured.
          format: date-time
        items:
          description: A list of all the items removed from inventory by this transaction
          type: array
          items:
            type: object
            required: [id, quantity, value]
            additionalProperties: false
            properties:
              id:
                type: string
                description: ID of the item affected by the transaction
              quantity:
                type: number
                description: Amount of the item purchased or created
              value:
                readOnly: true
                type: number
                maximum: 0
                description: |
                  Calculated value for this material, based on inventory at the time of sale.
                  This value will always be negative, as it _reduces_ the total value of inventory.
        totalCost:
          readOnly: true
          type: number
          # TODO Define if this should be a positive or negative number
          description: Calculated cost of goods sold in this transaction.

    Production:
      type: object
      description: |
        A transaction which converts some items into another via manufacturing processes.
        Multiple different `materials` may be consumed and the values of each are determined at the time of the transaction.
        Only one `product` can be produced, however, and its value is the sum total of all `materials` and `additionalCosts`.
      required: [id, materials, productId, productQuantity]
      additionalProperties: false
      properties:
        id:
          readOnly: true
          description: Globally-unique transaction ID
          type: string
          pattern: "[a-z0-9-]+"
        date:
          type: string
          description: When the transaction occured.
          format: date-time
        materials:
          description: A list of all the items consumed by manufacturing
          type: array
          items:
            type: object
            additionalProperties: false
            properties:
              id:
                type: string
                description: ID of the item affected by the transaction
              quantity:
                type: number
                description: Amount of the item purchased or created
              value:
                readOnly: true
                type: number
                # TODO Define if this should be a positive or negative number
                description: Calculated value for this material, based on inventory at the time of creation.
        additionalCosts:
          description: |
            Other costs, such as labor, that are directly attributed to the manufacturing.
            These are added to the material costs when calculating the manufactured item's value.
          type: array
          items:
            type: object
            additionalProperties:
              description: Additional information, such as tax jurisdiction, that may be needed for records
              type: string
            properties:
              name:
                type: string
                example: shipping
              cost:
                type: number
                # TODO Define if this should be a positive or negative number
        product:
          type: object
          additionalProperties: false
          properties:
            id:
              type: string
              description: ID of the item manufactured
            quantity:
              type: number
              description: Amount of the item manufactured
            value:
              readOnly: true
              type: number
              # TODO Define if this should be a positive or negative number
              description: Total calculated value of the item produced, including material and additional costs.


    Item:
      type: object
      required: [id]
      additionalProperties: false
      properties:
        id:
          readOnly: true
          type: string
          description: Unique ID or SKU of the material, part, or product.
          pattern: "[a-z0-9-]+"
          example: widget-blue-2in
        name:
          type: string
          description: Friendly name for display.
          example: 2" Blue Widget
        account:
          type: string
          description: The asset account associated with the item.
          enum:
            - Raw Materials
            - In-Progress
            - Finished
          default: Raw Materials
        unit:
          type: string
          description: |
            Unit of measure for the material.

            Examples:
            - each
            - bd.ft.
            - fl.oz.
          default: each
        quantity:
          readOnly: true
          type: number
          description: The quantity of the item currently in inventory.
          example: 2
        totalCost:
          readOnly: true
          type: number
          description: The total cost of all the units currently in inventory.
          example: 4.00
        unitCost:
          readOnly: true
          type: number
          description: The per-unit cost of each unit currently in inventory.
          example: 2.00
        hidden:
          type: boolean
          description: If `true`, the item should be hidden from selection lists and displays.
          default: false
        lastUpdated:
          readOnly: true
          type: string
          format: date-time
          description: The timestamp of the last transaction used to update this inventory.
