openapi: "3.0.0"

info:
  title: Northroad Craftworks Inventory
  version: Development

tags:
  - name: Service
    description: Information about the service's status
  - name: Inventory Items
    description: Manage inventory items
  - name: Transactions
    description: Buy, sell, manufacture, and adjust items in inventory

paths:
  /status:
    get:
      operationId: getStatus
      summary: Get the service status
      tags: [Service]
      responses:
        "200":
          description: General information about the health and status of the service.
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    description: Current release version
                    example: 1.0.0
  /items:
    get:
      operationId: listItems
      summary: List inventory items
      tags: [Inventory Items]
      responses:
        "200":
          description: All inventory items
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
        default:
          description: An error occurred

  /item/{itemId}:
    parameters:
      - $ref: "#/components/parameters/inventoryItemId"
    get:
      operationId: readItem
      summary: Get an inventory item
      tags: [Inventory Items]
      responses:
        "200":
          description: Details about the inventory item
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Item"
        default:
          description: An error occurred
    put:
      operationId: createItem
      summary: Create an inventory item
      tags: [Inventory Items]
      requestBody:
        description: Inventory item data
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "201":
          description: Inventory item created
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Item"
        "200":
          description: Inventory item updated
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Item"
        default:
          description: An error occurred
    
    patch:
      operationId: updateItem
      summary: Update an inventory item
      tags: [Inventory Items]
      requestBody:
        description: Updates to inventory data
        content:
          "application/json":
            schema:
              type: object
              properties:
                $ref: "#/components/schemas/Item/properties"
      responses:
        "200":
          description: Inventory item updated
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Item"
        default:
          description: An error occurred
    delete:
      operationId: deleteItem
      summary: Delete an unused inventory item
      description: |
        Inventory items can only be deleted if they haven't been used for any transactions and don't exist on any
        ledgers. Once an inventory item has been bought, sold, or manufactured, it cannot be deleted until **all**
        transactions which reference it have been deleted or archived.
      tags: [Inventory Items]
      deprecated: true
      responses:
        "501":
          description: Not implemented

  /buy:
    post:
      operationId: recordBuyTransaction
      summary: Record the purchase of new inventory
      tags: [Transactions]
      deprecated: true
      responses:
        "501":
          description: Not implemented

  /sell:
    post:
      operationId: recordSellTransaction
      summary: Record the sale of inventory to customers
      tags: [Transactions]
      deprecated: true
      responses:
        "501":
          description: Not implemented

  /manufacture:
    post:
      operationId: recordManufactureTransaction
      summary: Manufacture new inventory items from existing ones
      tags: [Transactions]
      deprecated: true
      responses:
        "501":
          description: Not implemented

  /adjust:
    post:
      operationId: recordManufactureTransaction
      summary: Manually adjust inventory items as the result of loss, damage, waste, or audits
      tags: [Transactions]
      deprecated: true
      responses:
        "501":
          description: Not implemented

components:
  parameters:
    inventoryItemId:
      name: itemId
      in: path
      required: true
      description: Item `id` of the desired item.
      schema:
        readOnly: false
        $ref: "#/components/schemas/Item/properties/id"

  schemas:
    InventoryTransaction:
      type: object
      properties:
        timestamp:
          type: string
          description: The timestamp of when the transaction occured.

    PurchaseTransaction:
      type: object
      properties:
        date:
          type: string
          description: When the transaction occured.
        items:
          type: array
          description: A list of all the materials purchased, and their costs.
          items:
            type: object
            required: [description, quantity, cost, unitCost]
            properties:
              description:
                type: string
                description: Description of the line item.
              inventoryId:
                $ref: "#/components/schemas/Item/properties/id"
              quantity:
                type: number
                description: The amount of the material purchased.
              cost:
                type: number
                description: The total cost of the material.
              unitCost:
                readOnly: true
                description: The cost per unit.
        # TODO Add a discount, which can be applied to item costs.
        shipping:
          type: number
          description: The amount spent on shipping expenses.
        tax:
          type: number
          description: The amount of tax paid.
        total:
          type: number
          description: The total amount of the transaction

    ManufactureTransaction:
      type: object
      properties:
        date:
          type: string
          description: The date of manufacturing
        materials:
          type: array
          description: A list of all the materials consumed in the product.
          items:
            type: object
            required: [inventoryId, quantity, cost, unitCost]
            properties:
              inventoryId:
                $ref: "#/components/schemas/Item/properties/id"
              quantity:
                type: number
                description: The amount of the material purchased.
              cost:
                readOnly: true
                type: number
                description: The total cost of the material.
              unitCost:
                readOnly: true
                description: The cost per unit.
        product:
          type: object
          description: The product produced.
          properties:
            inventoryId:
              $ref: "#/components/schemas/Item/properties/id"
            quantity:
              type: number
              description: The amount of the product produced.
            cost:
              readOnly: true
              type: number
              description: The total cost-of-goods-manufactered (COGM).
            unitCost:
              readOnly: true
              description: The cost-of-goods-manufactered (COGM) per unit.

    SaleTransaction:
      type: object
      properties:
        date:
          type: string
          description: The date of manufacturing
        items:
          type: array
          description: A list of all the items sold
          items:
            type: object
            required: [inventoryId, quantity, cost, unitCost]
            properties:
              inventoryId:
                $ref: "#/components/schemas/Item/properties/id"
              quantity:
                type: number
                description: The amount of the material purchased.
              cost:
                readOnly: true
                type: number
                description: The total cost of the material.
              unitCost:
                readOnly: true
                description: The cost per unit.

    Item:
      type: object
      required: [id, name, account]
      properties:
        id:
          readOnly: true
          type: string
          description: Unique ID or SKU of the material, part, or product.
          pattern: "[a-z0-9-]+"
          example: widget-blue-2in
        name:
          type: string
          description: Friendly name for display.
          example: 2" Blue Widget
        account:
          type: string
          description: The asset account associated with the item.
          enum:
            - Raw Materials
            - In-Progress
            - Finished
        unit:
          type: string
          description: |
            Unit of measure for the material.

            Examples:
            - each
            - bd.ft.
            - fl.oz.
          default: each
        quantity:
          readOnly: true
          type: number
          description: The quantity of the item currently in inventory.
          example: 2
        totalCost:
          readOnly: true
          type: number
          description: The total cost of all the units currently in inventory.
          example: 4.00
        unitCost:
          readOnly: true
          type: number
          description: The per-unit cost of each unit currently in inventory.
          example: 2.00
        hidden:
          type: boolean
          description: If `true`, the item should be hidden from selection lists and displays.
          default: false
        lastUpdated:
          readOnly: true
          type: string
          format: date-time
          description: The timestamp of the last transaction used to update this inventory.
